services:
    icantdecide_app.question_factory:
        class: GBProd\ICantDecide\CoreDomain\Question\QuestionFactory
        
    icantdecide_app.question_repository:
        class: GBProd\ICantDecide\Infrastructure\Question\DoctrineQuestionRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@rulerz"

    icantdecide_app.available_question_handler:
        class: GBProd\ICantDecide\Application\Handler\AvailableQuestionsHandler
        arguments:
            - "@icantdecide_app.question_repository"
        tags:
            -
                name: tactician.handler
                command: GBProd\ICantDecide\Application\Query\AvailableQuestionsQuery

    icantdecide_app.ask_question_handler:
        class: GBProd\ICantDecide\Application\Handler\AskQuestionHandler
        arguments:
            - "@icantdecide_app.question_repository"
            - "@icantdecide_app.question_factory"
        tags:
            -
                name: tactician.handler
                command: GBProd\ICantDecide\Application\Command\AskQuestionCommand
