question_index:
    path: /
    defaults:  { _controller: icantdecide.question.index_controller:index }
    
question_ask:
    path: /ask
    defaults:  { _controller: icantdecide.question.ask_controller:ask }