services:
    icantdecide.question_controller:
        class: GBProd\ICantDecide\UI\Controller\QuestionController
        arguments:
            - '@tactician.commandbus'
            - '@templating'
            - '@form.factory'
            - '@router'
            - '@session'

    icantdecide.ask_question_command:
        class: GBProd\ICantDecide\UI\Command\AskQuestionCommand
        arguments:
            - '@tactician.commandbus'
        tags:
            - { name: console.command }

    icantdecide.available_questions_command:
        class: GBProd\ICantDecide\UI\Command\AvailableQuestionsCommand
        arguments:
            - '@tactician.commandbus'
        tags:
            - { name: console.command }
