services:
    icantdecide.question_controller:
        class: GBProd\ICantDecide\UI\Controller\QuestionController
        arguments:
            - '@tactician.commandbus'
            - '@templating'
            - '@form.factory'